// utils/ota.js — 云端固件升级
const VERSION_URL = 'https://raw.githubusercontent.com/12668426/rinse-washer/main/ota/version.json'
const ble = require('./ble.js')
function cmpVer(a, b) { const pa = a.split('.').map(Number), pb = b.split('.').map(Number); for (let i = 0; i < 3; i++) { const da = pa[i] || 0, db = pb[i] || 0; if (da > db) return 1; if (da < db) return -1; } return 0 }
function checkUpdate(currentVer) { return new Promise((resolve, reject) => { wx.request({ url: VERSION_URL, method: 'GET', timeout: 10000, success: (res) => { if (res.statusCode !== 200) { reject(new Error('HTTP ' + res.statusCode)); return } const info = res.data; resolve({ version: info.version, url: info.url, size: info.size || 0, notes: info.notes || '', hasUpdate: cmpVer(info.version, currentVer) > 0 }) }, fail: (err) => reject(new Error('网络失败：' + err.errMsg)) }) }) }
function downloadFirmware(url) { return new Promise((resolve, reject) => { wx.downloadFile({ url, success: (res) => { if (res.statusCode !== 200) { reject(new Error('HTTP ' + res.statusCode)); return } resolve({ tempFilePath: res.tempFilePath }) }, fail: (err) => reject(new Error('下载失败：' + err.errMsg)) }) }) }
function readFileAsArrayBuffer(filePath) { return new Promise((resolve, reject) => { wx.getFileSystemManager().readFile({ filePath, success: (res) => resolve(res.data), fail: (err) => reject(new Error('读取失败：' + err.errMsg)) }) }) }
function base64Encode(ab) { return wx.arrayBufferToBase64 ? wx.arrayBufferToBase64(ab) : '' }
async function pushFirmware(arrayBuffer, onProgress) { const CHUNK = 4096, total = arrayBuffer.byteLength, chunks = Math.ceil(total / CHUNK); onProgress && onProgress('begin', 0); await ble.send({ cmd: 'ota_begin', size: total }); for (let i = 0; i < chunks; i++) { const off = i * CHUNK, end = Math.min(off + CHUNK, total); const b64 = base64Encode(arrayBuffer.slice(off, end)); await ble.send({ cmd: 'ota_data', seq: i, data: b64 }); onProgress && onProgress('data', Math.round((i + 1) / chunks * 100)) } onProgress && onProgress('end', 100); await ble.send({ cmd: 'ota_end' }) }
module.exports = { checkUpdate, downloadFirmware, readFileAsArrayBuffer, pushFirmware, cmpVer }
